@Circles.Index.Rpc.Host_HostAddress = http://localhost:5079

GET {{Circles.Index.Rpc.Host_HostAddress}}/todos/
Accept: application/json

###

GET {{Circles.Index.Rpc.Host_HostAddress}}/todos/1
Accept: application/json

###
