services:
  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.0
    restart: unless-stopped
    user: root
    networks:
      - circles-gnosis
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3002}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ../.state/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
